### ISSUE TITLE
some API improve

### ISSUE THREAD

**Issue by starwing** [mkottman/luaclang-parser#1]
hi mike :)

I have read the document of luaclang, maybe some API of it can improve:
- cursor/type's serveral functions may use __newindex to retrieve directly.
- children() can return a iterator, like this:
  for idx, node in cur:children() do
  ...
  end
- cursor can have a # operator, to get the count of children.
- you can retrieve node with cur[idx] syntax.
- in lua5.2, you can add __ipairs metamethod.

I'm a little busy these days ( have fired second time :( I will try to make a libclang binding based from yours using my lbind runtime, that will make cursor/type more like reguiar tables. maybe we can use cursor/type directly in generator.

and very very thank you for your pioneer work :)

regards,
Xavier Wang.

**Comment by mkottman** [comment]
Hi, thanks for suggestions, here are my thoughts:
- I'm not sure using `__newindex` would help, why would I want to set a cursor to something? The API is supposed to be read-olny
- I like the way `children()` is done, because now I can check whether a cursor has children using `#` on an the resulting array, but I guess `#` on cursor directly would be ok.
- I am targeting Lua 5.1 primarily, not sure the `__ipairs` metamethod would be a win :)

As was discussed on the list, my work is not pioneer, just first to publicly speak about it :)

**Comment by starwing** [comment]
sorry for that, i mean __index...
ÔÚ 2012-7-13 ÏÂÎç5:20£¬"Michal Kottman" <
reply@reply.github.com

**Comment by mkottman** [comment]
Now that I though about it a bit more, it would not be straight forward to do cursor API change to an iterator. On the Clang side, you have to [traverse the AST using callbacks](http://clang.llvm.org/doxygen/group__CINDEX__CURSOR__TRAVERSAL.html). This would mean that in order to count the number of children, you would have to have a special callback, and then to access it as an iterator, you would have to have another special callback, and to access it using `__index`, a third version of a callback.

Gathering the results to a table array is in my opinion the cleanest way to handle this issue.

**Comment by starwing** [comment]
thanks very much for you explain :)

I just built clang, it's time to look into it.
